# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# 300.times do |u|
#     MusicAlbum.create(name: Faker::Music.album, band: Faker::Music.band, genre: Faker::Music.genre)
# end

#  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# THE WORST SEED EVER
MusicAlbum.create(name: "Hounds of Love", band: "Kate Bush", genre: "Pop/Rock", year: 1985)
MusicAlbum.create(name: "Born This Way", band: "Lady Gaga", genre: "Pop", year: 2011)
MusicAlbum.create(name: "Red", band: "Taylor Swift", genre: "Pop/Country", year: 2012)
MusicAlbum.create(name: "++", band: "LOONA", genre: "K-Pop", year: 2018)
MusicAlbum.create(name: "Live Through This", band: "Hole", genre: "Grunge/Alternative Rock", year: 1994)
MusicAlbum.create(name: "Start→", band: "Silent Siren", genre: "J-Pop/Rock", year: 2012)
MusicAlbum.create(name: "The Kick Inside", band: "Kate Bush", genre: "Art Pop", year: 1978)
MusicAlbum.create(name: "The Fame", band: "Lady Gaga", genre: "Pop/Electronic", year: 2008)
MusicAlbum.create(name: "1989", band: "Taylor Swift", genre: "Pop", year: 2014)
MusicAlbum.create(name: "[+ +]", band: "LOONA", genre: "K-Pop", year: 2018)
MusicAlbum.create(name: "Celebrity Skin", band: "Hole", genre: "Alternative Rock", year: 1998)
MusicAlbum.create(name: "S", band: "Silent Siren", genre: "J-Pop/Rock", year: 2012)
MusicAlbum.create(name: "Hounds of Love", band: "Kate Bush", genre: "Pop/Rock", year: 1985)
MusicAlbum.create(name: "ARTPOP", band: "Lady Gaga", genre: "Pop/Electronic", year: 2013)
MusicAlbum.create(name: "Speak Now", band: "Taylor Swift", genre: "Pop/Country", year: 2010)
MusicAlbum.create(name: "[X X]", band: "LOONA", genre: "K-Pop", year: 2019)
MusicAlbum.create(name: "Live Through This", band: "Hole", genre: "Grunge/Alternative Rock", year: 1994)
MusicAlbum.create(name: "S", band: "Silent Siren", genre: "J-Pop/Rock", year: 2012)
MusicAlbum.create(name: "The Dreaming", band: "Kate Bush", genre: "Art Pop", year: 1982)
MusicAlbum.create(name: "Joanne", band: "Lady Gaga", genre: "Pop/Country", year: 2016)
MusicAlbum.create(name: "Fearless", band: "Taylor Swift", genre: "Pop/Country", year: 2008)
MusicAlbum.create(name: "[12:00]", band: "LOONA", genre: "K-Pop", year: 2020)
MusicAlbum.create(name: "Celebrity Skin", band: "Hole", genre: "Alternative Rock", year: 1998)
MusicAlbum.create(name: "Silent Siren", band: "Silent Siren", genre: "J-Pop/Rock", year: 2012)
MusicAlbum.create(name: "Hounds of Love", band: "Kate Bush", genre: "Pop/Rock", year: 1985)
MusicAlbum.create(name: "Born This Way", band: "Lady Gaga", genre: "Pop", year: 2011)
MusicAlbum.create(name: "Lover", band: "Taylor Swift", genre: "Pop", year: 2019)
MusicAlbum.create(name: "[&]", band: "LOONA", genre: "K-Pop", year: 2021)
MusicAlbum.create(name: "Pretty on the Inside", band: "Hole", genre: "Grunge/Alternative Rock", year: 1991)
MusicAlbum.create(name: "Cherry Bomb", band: "Silent Siren", genre: "J-Pop/Rock", year: 2014)
MusicAlbum.create(name: "The Sensual World", band: "Kate Bush", genre: "Art Pop", year: 1989)
MusicAlbum.create(name: "The Fame Monster", band: "Lady Gaga", genre: "Pop/Electronic", year: 2009)
MusicAlbum.create(name: "Evermore", band: "Taylor Swift", genre: "Pop/Folk", year: 2020)
MusicAlbum.create(name: "[#]", band: "LOONA", genre: "K-Pop", year: 2020)
MusicAlbum.create(name: "Live Through This", band: "Hole", genre: "Grunge/Alternative Rock", year: 1994)
MusicAlbum.create(name: "Girls Power", band: "Silent Siren", genre: "J-Pop/Rock", year: 2013)
MusicAlbum.create(name: "Never for Ever", band: "Kate Bush", genre: "Art Pop", year: 1980)
MusicAlbum.create(name: "Cheek to Cheek", band: "Lady Gaga", genre: "Jazz/Pop", year: 2014)
MusicAlbum.create(name: "Folklore", band: "Taylor Swift", genre: "Alternative/Indie", year: 2020)
MusicAlbum.create(name: "[12:00]", band: "LOONA", genre: "K-Pop", year: 2020)
MusicAlbum.create(name: "Celebrity Skin", band: "Hole", genre: "Alternative Rock", year: 1998)
MusicAlbum.create(name: "Love Is Born", band: "Silent Siren", genre: "J-Pop/Rock", year: 2015)
MusicAlbum.create(name: "The Red Shoes", band: "Kate Bush", genre: "Art Pop", year: 1993)
MusicAlbum.create(name: "Chromatica", band: "Lady Gaga", genre: "Pop/Dance", year: 2020)
MusicAlbum.create(name: "Reputation", band: "Taylor Swift", genre: "Pop", year: 2017)
MusicAlbum.create(name: "[&]", band: "LOONA", genre: "K-Pop", year: 2021)
MusicAlbum.create(name: "Nobody's Daughter", band: "Hole", genre: "Alternative Rock", year: 2010)
MusicAlbum.create(name: "Mix10", band: "Silent Siren", genre: "J-Pop/Rock", year: 2018)
MusicAlbum.create(name: "The Sensual World", band: "Kate Bush", genre: "Art Pop", year: 1989)
MusicAlbum.create(name: "Artpop", band: "Lady Gaga", genre: "Pop/Electronic", year: 2013)
MusicAlbum.create(name: "Born to Die", band: "Lana Del Rey", genre: "Indie Pop", year: 2012)
MusicAlbum.create(name: "Donde Está el País de las Hadas", band: "Mecano", genre: "Pop", year: 1988)
MusicAlbum.create(name: "Lust for Life", band: "Lana Del Rey", genre: "Indie Pop", year: 2017)
MusicAlbum.create(name: "Descanso Dominical", band: "Mecano", genre: "Pop", year: 1988)
MusicAlbum.create(name: "Ultraviolence", band: "Lana Del Rey", genre: "Indie Pop", year: 2014)
MusicAlbum.create(name: "Aidalai", band: "Mecano", genre: "Pop", year: 1991)
MusicAlbum.create(name: "Honeymoon", band: "Lana Del Rey", genre: "Indie Pop", year: 2015)
MusicAlbum.create(name: "Ana Jose Nacho", band: "Mecano", genre: "Pop", year: 1998)
MusicAlbum.create(name: "Norman Fucking Rockwell!", band: "Lana Del Rey", genre: "Indie Pop", year: 2019)
MusicAlbum.create(name: "Aidalai", band: "Mecano", genre: "Pop", year: 1991)
MusicAlbum.create(name: "Chemtrails Over the Country Club", band: "Lana Del Rey", genre: "Indie Pop", year: 2021)
MusicAlbum.create(name: "Descanso Dominical", band: "Mecano", genre: "Pop", year: 1988)
MusicAlbum.create(name: "Born to Die", band: "Lana Del Rey", genre: "Indie Pop", year: 2012)
MusicAlbum.create(name: "Aidalai", band: "Mecano", genre: "Pop", year: 1991)
MusicAlbum.create(name: "Ultraviolence", band: "Lana Del Rey", genre: "Indie Pop", year: 2014)
MusicAlbum.create(name: "Descanso Dominical", band: "Mecano", genre: "Pop", year: 1988)
MusicAlbum.create(name: "Honeymoon", band: "Lana Del Rey", genre: "Indie Pop", year: 2015)
MusicAlbum.create(name: "Ana Jose Nacho", band: "Mecano", genre: "Pop", year: 1998)
MusicAlbum.create(name: "Norman Fucking Rockwell!", band: "Lana Del Rey", genre: "Indie Pop", year: 2019)
MusicAlbum.create(name: "Aidalai", band: "Mecano", genre: "Pop", year: 1991)
MusicAlbum.create(name: "Chemtrails Over the Country Club", band: "Lana Del Rey", genre: "Indie Pop", year: 2021)